
format = """
[┌─ ](bold white)$shell$time$directory$git_branch$git_status$cmd_duration\
 $c\
 $dotnet\
 $elixir\
 $elm\
 $golang\
 $haskell\
 $java\
 $julia\
 $nodejs\
 $nim\
 $rust\
 $scala
[└─](bold white)$character"""

scan_timeout = 10

[character]
success_symbol = "[❯❯❯](bold white) "
error_symbol =   "[❯❯❯](bold red) "

[shell]
disabled = false
format = "${indicator}"
fish_indicator = "><>"
powershell_indicator = ">_"
zsh_indicator = "[z]"
bash_indicator = "$_"
unknown_indicator = "[?]"

[directory]
style = "bold blue underline"
read_only_style = "🔒"
format = "[$read_only]($read_only_style)[$path]($style) "
truncation_length = 5 
truncation_symbol = ".../"

[directory.substitutions]
"documents" = " "
"Documents" = " "
"downloads" = " "
"Downloads" = " "
"music" = " "
"Music" = " "
"pictures" = " "
"Pictures" = " "
"Code" = "󰘧"
"code" = "󰘧"


[git_status]
conflicted = "="
untracked  = "?"
# stashed    = "'$'"
modified   = "!"
staged     = "+"
renamed    = "~"
deleted    = "✘"
style = "bold yellow"
ahead = "▲${count}"
behind = "▼${count}"
diverged = "♦ ▲${ahead_count} ▼${behind_count}"

[cmd_duration]
format = "took [$duration](bold white)"

[time]
disabled = true
format = '[\[$time\]](bold white) '
time_format = "%T"
utc_time_offset = "+9"

[status]
style = "red"
symbol = "✖"
not_executable_symbol = "🚫"
not_found_symbol = "🔍"
sigint_symbol = "⚡"
signal_symbol = "⚡"
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[golang]
symbol = " "
style = "fg:#11111b bg:##cba6f7"
#format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'
format = '[[ $symbol](fg:#11111b bg:#cba6f7)]($style)'
[haskell]
symbol = " "
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[java]
symbol = " "
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[julia]
symbol = " "
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[nodejs]
symbol = ""
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[nim]
symbol = " "
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[rust]
symbol = ""
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[dotnet]
symbol = ""
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[scala]
symbol = ""
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'
