---- import metals safely
-- local metals_status, metals = pcall(require, "metals")
-- if not metals_status then
--   return
-- end
--
--
-- -- Create the configuration for metals
-- local metals_config = require("metals").bare_config()
--
-- metals_config.capabilities = require("cmp_nvim_lsp").default_capabilities()
-- ---
-- -- Autocmd that will actually be in charging of starting metals
-- ---
-- -- Debug settings if you're using nvim-dap
-- local dap = require("dap")
--
-- dap.configurations.scala = {
-- 	{
-- 		type = "scala",
-- 		request = "launch",
-- 		name = "RunOrTest",
-- 		metals = {
-- 			runType = "runOrTestFile",
-- 			--args = { "firstArg", "secondArg", "thirdArg" }, -- here just as an example
-- 		},
-- 	},
-- 	{
-- 		type = "scala",
-- 		request = "launch",
-- 		name = "Test Target",
-- 		metals = {
-- 			runType = "testTarget",
-- 		},
-- 	},
-- }
--
-- metals_config.on_attach = function(client, bufnr)
-- 	require("metals").setup_dap()
-- end
--
-- local nvim_metals_group = vim.api.nvim_create_augroup("nvim-metals", { clear = true })
-- vim.api.nvim_create_autocmd("FileType", {
-- 	pattern = { "scala", "sbt", "java" },
-- 	callback = function()
-- 		require("metals").initialize_or_attach(metals_config)
-- 	end,
-- 	group = nvim_metals_group,
-- })
--
