-- return {
--   "kdheepak/lazygit.nvim",
--   dependencies = {
--     "nvim-lua/plenary.nvim",
--   },
--   config = function()
--     local lazygit = require("lazygit")
--     local plenary = require("plenary")
--     lazygit.setuo({
--       cmd = {
--         "LazyGit",
--         "LazyGitConfig",
--         "LazyGitCurrentFile",
--         "LazyGitFilter",
--         "LazyGitFilterCurrentFile",
--       },
--       -- optional for floating window border decoration
--       -- setting the keybinding for LazyGit with 'keys' is recommended in
--       -- order to load the plugin when the command is run for the first time
--       keys = {
--         { "<leader>lg", "<cmd>LazyGit<cr>", desc = "LazyGit" },
--       },
--     })
--   end,
-- }
